const { test } = require('node:test');
const assert = require('node:assert/strict');

test('login, refresh, reservation ownership, confirmation and logout', {
  skip: !process.env.MONGO_TEST_URI,
  timeout: 30000
}, async () => {
  const uri = process.env.MONGO_TEST_URI;
  assert.match(uri, /^mongodb:\/\/127\.0\.0\.1:\d+\/canchalibre_test(?:\?|$)/, 'Only an isolated local test database is allowed');
  process.env.MONGO_URI = uri;
  process.env.JWT_ACCESS_SECRET = 'integration-only-secret';
  process.env.JWT_SECRET = 'integration-only-secret';
  process.env.NODE_ENV = 'test';
  process.env.FRONT_URL = 'http://localhost:8080';
  process.env.MP_ACCESS_TOKEN = 'TEST-isolated';
  const mongoose = require('mongoose');
  const express = require('express');
  const cron = require('node-cron');
  const sent = [];
  const emailPath = require.resolve('../utils/email');
  require.cache[emailPath] = { id: emailPath, filename: emailPath, loaded: true, exports: { sendMail: async (...args) => { sent.push(args); } } };
  const mercadopago = require('../utils/mercadopago');
  const originalPaymentLookup = mercadopago.payment.findById;
  let paymentResponse;
  mercadopago.payment.findById = async (id, options) => {
    assert.equal(options.access_token, 'TEST-private-club-token');
    return { body: paymentResponse };
  };
  const originalSchedule = cron.schedule;
  cron.schedule = () => ({ stop() {} });
  const originalListen = express.application.listen;
  let server;
  express.application.listen = function () { server = originalListen.call(this, 0, '127.0.0.1'); return server; };
  try {
    require('../server');
    await mongoose.connection.asPromise();
    if (!server.listening) await new Promise(resolve => server.once('listening', resolve));
    const base = 'http://127.0.0.1:' + server.address().port;
    const Usuario = require('../models/Usuario');
    const Club = require('../models/Club');
    const Cancha = require('../models/Cancha');
    const Reserva = require('../models/Reserva');
    const Turno = require('../models/Turno');
    await Promise.all([Usuario.init(), Club.init(), Reserva.init(), Turno.init()]);
    const password = 'Integration-test-123!';
    const passwordHash = await require('bcryptjs').hash(password, 4);
    const user = await Usuario.create({ email: 'owner@canchalibre.local', passwordHash, emailVerificado: true });
    await Usuario.create({ email: 'other@canchalibre.local', passwordHash, emailVerificado: true });
    await Club.create({ nombre: 'Test Club', email: 'club@canchalibre.local', telefono: '123', provincia: 'Cordoba', localidad: 'Test', passwordHash, mercadoPagoAccessToken: 'TEST-private-club-token' });
    const clubFixture = await Club.findOne({ email: 'club@canchalibre.local' });
    const clubToken = require('jsonwebtoken').sign({ clubId: String(clubFixture._id) }, process.env.JWT_SECRET);
    const cancha = await Cancha.create({ nombre: 'Test Court', clubEmail: 'club@canchalibre.local', deporte: 'padel', precio: 1000, horaDesde: '08:00', horaHasta: '22:00', diasDisponibles: ['jueves'], duracionTurno: 60 });
    async function request(path, { token, cookie, body, method = 'GET' } = {}) {
      const headers = {};
      if (token) headers.Authorization = 'Bearer ' + token;
      if (cookie) headers.Cookie = cookie;
      if (body) headers['Content-Type'] = 'application/json';
      return fetch(base + path, { method, headers, body: body ? JSON.stringify(body) : undefined, redirect: 'manual' });
    }
    const publicClub = await request('/club/club@canchalibre.local');
    const publicData = await publicClub.json();
    assert.equal(publicData.passwordHash, undefined);
    assert.equal(publicData.mercadoPagoAccessToken, undefined);
    assert.equal(publicData.pagoOnlineDisponible, true);
    assert.equal((await request('/turnos')).status, 401);
    assert.equal((await request('/editar-ubicacion-club', { method: 'PUT', body: { email: 'club@canchalibre.local', latitud: 0, longitud: 0 } })).status, 401);
    const privateClub = await request('/api/club/me', { token: clubToken });
    const privateData = await privateClub.json();
    assert.equal(privateData.passwordHash, undefined);
    assert.equal(privateData.mercadoPagoAccessToken, 'TEST-private-club-token');
    const clubBooking = { canchaId: String(cancha._id), deporte: 'padel', club: clubFixture.email, fecha: '2030-01-10', hora: '12:00', precio: 1000, usuarioReservado: 'Test', emailReservado: 'test@example.com', metodoPago: 'efectivo' };
    const concurrentBookings = await Promise.all([request('/reservar-turno', { method: 'POST', token: clubToken, body: clubBooking }), request('/reservar-turno', { method: 'POST', token: clubToken, body: clubBooking })]);
    assert.deepEqual(concurrentBookings.map(r => r.status).sort(), [200, 409]);
    const login = await request('/auth/login', { method: 'POST', body: { email: user.email, password } });
    assert.equal(login.status, 200);
    const { accessToken } = await login.json();
    const cookie = login.headers.get('set-cookie').split(';')[0];
    assert.match(login.headers.get('set-cookie'), /HttpOnly/);
    assert.match(login.headers.get('set-cookie'), /Path=\/auth/);
    assert.equal((await request('/auth/me', { token: accessToken })).status, 200);
    const refreshResults = await Promise.all([request('/auth/refresh', { method: 'POST', cookie }), request('/auth/refresh', { method: 'POST', cookie })]);
    assert.deepEqual(refreshResults.map(r => r.status).sort(), [200, 401]);
    const refreshed = refreshResults.find(r => r.status === 200);
    const renewed = await refreshed.json();
    const newCookie = refreshed.headers.get('set-cookie').split(';')[0];
    assert.equal((await request('/auth/refresh', { method: 'POST', cookie })).status, 401);
    const hold = await request('/reservas/hold', { method: 'POST', token: renewed.accessToken, body: {
      canchaId: String(cancha._id), fecha: '2030-01-10', hora: '10:00', metodoPago: 'efectivo', email: 'spoof@canchalibre.local'
    } });
    assert.equal(hold.status, 200);
    const { reservaId } = await hold.json();
    const reserva = await Reserva.findById(reservaId);
    assert.equal(String(reserva.usuarioId), String(user._id));
    assert.equal(reserva.emailContacto, user.email);
    assert.equal(sent[0][0], user.email);
    const guestHold = await request('/reservas/hold', { method: 'POST', body: { canchaId: String(cancha._id), fecha: '2030-01-10', hora: '16:00', email: 'guest@example.com', usuarioId: String(user._id), metodoPago: 'efectivo' } });
    assert.equal(guestHold.status, 200);
    const guestReservation = await Reserva.findById((await guestHold.json()).reservaId);
    assert.equal(guestReservation.usuarioId, null);
    const otherLogin = await request('/auth/login', { method: 'POST', body: { email: 'other@canchalibre.local', password } });
    const otherToken = (await otherLogin.json()).accessToken;
    assert.equal((await request('/api/me/reservas/' + reservaId + '/cancel', { method: 'PATCH', token: otherToken })).status, 404);
    const list = await request('/api/me/reservas', { token: renewed.accessToken });
    const listed = await list.json();
    assert.equal(listed.length, 1);
    assert.equal(listed[0].codigoOTP, undefined);
    assert.equal((await request('/reservar-turno', { method: 'POST', body: {} })).status, 401);
    assert.equal((await request('/auth/refresh', { method: 'POST', cookie: 'canchalibre_refresh=%zz' })).status, 401);
    const confirm = await request('/reservas/confirmar/' + reservaId + '/' + reserva.codigoOTP);
    assert.equal(confirm.status, 302);
    assert.equal((await Reserva.findById(reservaId)).estado, 'CONFIRMED');
    const turno = await Turno.findOne({ canchaId: String(cancha._id) });
    assert.equal(String(turno.usuarioId), String(user._id));
    const availability = await request('/turnos-generados?fecha=2030-01-10');
    const slots = await availability.json();
    assert.ok(slots.length > 0);
    assert.ok(slots.every(slot => slot.emailReservado === null));
    assert.ok(!JSON.stringify(slots).includes(user.email));
    const webhook = '/api/mercadopago/webhook?club=club%40canchalibre.local&turno=' + turno._id;
    paymentResponse = { status: 'pending', external_reference: String(turno._id), transaction_amount: turno.precio, currency_id: 'ARS' };
    assert.equal((await request(webhook, { method: 'POST', body: { data: { id: 'test-payment' } } })).status, 200);
    assert.equal((await Turno.findById(turno._id)).pagado, false);
    paymentResponse = { ...paymentResponse, status: 'approved', transaction_amount: 1 };
    assert.equal((await request(webhook, { method: 'POST', body: { data: { id: 'test-payment' } } })).status, 400);
    assert.equal((await Turno.findById(turno._id)).pagado, false);
    paymentResponse.transaction_amount = turno.precio;
    assert.equal((await request(webhook, { method: 'POST', body: { data: { id: 'test-payment' } } })).status, 200);
    assert.equal((await Turno.findById(turno._id)).pagado, true);
    assert.equal((await request(webhook, { method: 'POST', body: { data: { id: 'test-payment' } } })).status, 200);
    assert.equal(await require('../models/PaymentEvent').countDocuments({ paymentId: 'test-payment' }), 1);
    assert.equal((await request('/api/me/turnos/' + turno._id + '/cancel', { method: 'PATCH', token: otherToken })).status, 404);
    assert.equal((await request('/api/me/turnos/' + turno._id + '/cancel', { method: 'PATCH', token: renewed.accessToken })).status, 409);
    await Turno.updateOne({ _id: turno._id }, { $set: { pagado: false } });
    assert.equal((await request('/api/me/turnos/' + turno._id + '/cancel', { method: 'PATCH', token: renewed.accessToken })).status, 200);
    assert.equal((await Turno.findById(turno._id)).usuarioId, null);
    assert.equal((await Reserva.findById(reservaId)).estado, 'CANCELLED');
    const conflicts = await Reserva.create([1, 2].map(n => ({ canchaId: cancha._id, usuarioId: user._id, emailContacto: user.email, fecha: '2030-01-10', hora: '14:00', codigoOTP: String(100000 + n), expiresAt: new Date(Date.now() + 600000) })));
    const confirmed = await Promise.all(conflicts.map(r => request('/reservas/confirmar/' + r._id + '/' + r.codigoOTP)));
    assert.deepEqual(confirmed.map(r => r.status).sort(), [302, 409]);
    assert.equal(await Turno.countDocuments({ canchaId: String(cancha._id), fecha: '2030-01-10', hora: '14:00' }), 1);
    assert.equal((await request('/auth/logout', { method: 'POST', cookie: newCookie })).status, 200);
    assert.equal((await request('/auth/refresh', { method: 'POST', cookie: newCookie })).status, 401);
  } finally {
    express.application.listen = originalListen;
    cron.schedule = originalSchedule;
    mercadopago.payment.findById = originalPaymentLookup;
    if (server) await new Promise(resolve => server.close(resolve));
    await mongoose.disconnect();
  }
});
